universe                = docker
docker_image            = docker.lsv.uni-saarland.de/mrdupont/eamt:v1
executable              = /nethome/mrdupont/enumeration-aware-molecule-transformers/htcondor/adapt_parallel.py
environment             = "PROJECT_ROOT=/nethome/mrdupont/enumeration-aware-molecule-transformers WANDB_PROJECT=da4mt_$(YEAR)_$(MONTH)_$(DAY)"
initialdir              = /nethome/mrdupont/
output                  = /data/users/mrdupont/da4mt/logs/adapt_parallel.$(ClusterId).$(ProcId).out
error                   = /data/users/mrdupont/da4mt/logs/adapt_parallel.$(ClusterId).$(ProcId).err
log                     = /data/users/mrdupont/da4mt/logs/adapt_parallel.$(ClusterId).$(ProcId).log
stream_output           = True
transfer_output         = True
request_CPUs = 12
request_GPUS = 1
requirements = (GPUs_GlobalMemoryMb >= 12000) && (machine == "cl18lx.lsv.uni-saarland.de")
request_memory = 35G
queue arguments from (
    "mlm-bert-30"
    "mlm-bert-60"
    "mlm-bert-100"
    "none-bert-0"
    "mtr-bert-30"
)
