universe                = docker
docker_image            = docker.lsv.uni-saarland.de/mrdupont/eamt:v1
executable              = /nethome/mrdupont/enumeration-aware-molecule-transformers/htcondor/compare.sh
environment             = "PROJECT_ROOT=/nethome/mrdupont/enumeration-aware-molecule-transformers"
initialdir              = /nethome/mrdupont/
output                  = /data/users/mrdupont/da4mt/logs/compare.$(ClusterId).out
error                   = /data/users/mrdupont/da4mt/logs/compare.$(ClusterId).err
log                     = /data/users/mrdupont/da4mt/logs/compare.$(ClusterId).log
stream_output           = True
transfer_output         = True
request_CPUs = 25
request_GPUS = 1
requirements = (GPUs_GlobalMemoryMb >= 12000) && (machine == "cl17lx.lsv.uni-saarland.de" || machine == "cl18lx.lsv.uni-saarland.de")
request_memory = 35G
queue 1
